---
- name: play level variables
  hosts: local
  connection: local
  tasks:
    - name: print variables
      vars:
         COURSE: DEVOPS
         DAYS: 140
         TUTOR: Shiva
      ansible.builtin.debug:
          msg: I will Complete {{ COURSE }} in {{ DAYS }} days