---
- name: variable preference
  hosts: local
  connection: local
  vars:
   - Name: Ansible vars from play
  # vars_files:
  #  - course.yaml
  vars_prompt:
   - name: Name
     prompt: enter your username
     private: false
  tasks:
    - name: print Name
      #vars:
      #  Name: "Ansible from Tasks"
      ansible.builtin.debug:
        msg: "Hi {{ Name }}"
