- name: demo on loops
  hosts: local
  connection: local
  become: true
  tasks:
    - name: print names
      ansible.builtin.package:
          name: "{{ item }}"
          state: present
      loop:
        - nginx
        - mysql
        - zip