- name: demo on filters
  hosts: local
  connection: local
  vars:
    details: Mahesh, devops, Test
    tagsMap:
      name: docker
      version: 1.21
      os: linux
    tagsList: [
            {
            "key": "name",
            "value": "ansible"
            },
            {
            "key": "project",
            "value": "roboshop"
            },
           {
            "key": "component",
            "value": "catalogue"
           }
    ]
  tasks:
   - name: Greeting
     ansible.builtin.debug: 
        msg: "Hi Mahesh {{ Greeting | default('Good Morning')}}"
   - name: Convert String to List
     ansible.builtin.debug:
        msg: "{{ details | split(',') }}"
   - name: Convert map to list
     ansible.builtin.debug:
        msg: "{{ tagsMap | dict2items }}" 
   - name: Convert List to map
     ansible.builtin.debug:
        msg: "{{ tagsList | items2dict }}" 
   - name: read students yaml
     ansible.builtin.set_fact: #setting the variable
       student_yaml: "{{ lookup( 'file','students.yml' ) | from_yaml }}"
   - name: convert yaml to json
     ansible.builtin.debug:
       msg: "{ student_yaml | to_nice_json }"