- name: demo on filters
  hosts: local
  connection: local
  vars:
    details: Mahesh, devops, Test
  tasks:
   - name: Greeting
     ansible.builtin.debug: 
        msg: "Hi Mahesh {{ Greeting | default('Good Morning')}}"
   - name: Convert String to List
     ansible.builtin.debug:
        msg: "{{ details | split(',') }}"